name: CI Behave Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *' # Ejecuta cada 24 horas (medianoche UTC)

jobs:
  behave-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar pruebas Behave y generar reporte
        env:
          CI: true
        run: |
          mkdir -p shophub_ui_test/reports/behave
          behave shophub_ui_test/features --format behave_html_formatter:HTMLFormatter --outfile shophub_ui_test/reports/behave/behave-report.html

      - name: Cargar artefactos de reporte
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: behave-report
          path: shophub_ui_test/reports/behave/behave-report.html
          if-no-files-found: ignore
